# Generated by Django 5.2.17 on 2026-09-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentface',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Normalized 512-d ArcFace embedding for THIS photo (null for photos registered before per-photo embeddings existed).', null=True),
        ),
    ]
