"""AI model / configuration registry for the Smart Attendance System.

All AI logic is isolated in this package and separated from Django business
logic. The recognition stack is a pre-trained pipeline (no training happens
in this project):

- Detection:  OpenCV YuNet (RetinaFace-style, ONNX)
- Embedding:  InsightFace ArcFace (w600k_r50, 512-d embeddings, ONNX)

Students are never "trained" from scratch. Instead each student is associated
with a compact 512-dimension normalized embedding generated by the ArcFace
model, and attendance matching is a fast cosine-similarity search against the
registered gallery.
"""
import os

from django.conf import settings

# Model files (downloaded once by scripts/download_models.py)
DETECTOR_MODEL_PATH = os.path.join(settings.AI_MODELS_DIR, settings.AI_DETECTOR_MODEL)
RECOGNITION_MODEL_PATH = os.path.join(settings.AI_MODELS_DIR, settings.AI_RECOGNITION_MODEL)

EMBEDDING_DIM = 512
CANONICAL_FACE_SIZE = 112

# Standard ArcFace alignment target landmarks (same convention as InsightFace).
TARGET_LANDMARKS = [
    (38.2946, 51.6963),  # right eye
    (73.5318, 51.5014),  # left eye
    (56.0252, 71.7366),  # nose tip
    (41.5493, 92.3655),  # right mouth corner
    (70.7299, 92.2041),  # left mouth corner
]

# Quality-gate thresholds (LOW_QUALITY reporting) - sourced from Django
# settings so each deployment can tune them through .env without code
# changes. See config/settings.py for how the defaults were measured.
MIN_FACE_PX = settings.RECOGNITION_MIN_FACE_PX
MIN_FACE_RATIO = settings.RECOGNITION_MIN_FACE_RATIO
MIN_DETECTOR_SCORE = settings.RECOGNITION_MIN_DETECTOR_SCORE
MIN_FACE_SHARPNESS = settings.RECOGNITION_MIN_FACE_SHARPNESS


def model_missing_message():
    return (
        "AI models are not downloaded yet. Run: "
        "python scripts/download_models.py  (or: python manage.py download_models)"
    )